In [34]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.metrics import accuracy_score

In [10]:
df = pd.read_csv("Decision_Tree_ Dataset.csv")

In [11]:
x=df.values[:,0:5]
y=df.values[:,-1]

In [12]:
print(x)

[[201 10018 250 3046 13515]
 [205 10016 395 3044 13660]
 [257 10129 109 3251 13746]
 ...
 [316 14872 613 4760 20561]
 [305 14926 897 4572 20700]
 [168 14798 834 4937 20737]]


In [13]:
#print(y)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42, test_size=0.3)

In [15]:
clf_entropy=DecisionTreeClassifier(criterion='entropy',random_state=100,max_depth=3,min_samples_leaf=5)

In [16]:
clf_entropy.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [22]:
y_pred_en = clf_entropy.predict(x_test)

In [36]:
print('Accuracy is : '),accuracy_score(y_test,y_pred_en)*100

Accuracy is : 


(None, 100.0)

In [24]:
from sklearn.svm import SVC
svm_classifier=SVC(kernel='rbf',random_state=56,gamma='scale',C=1.0)

In [27]:
svm_classifier.fit(x_train,y_train)

SVC(random_state=56)

In [30]:
y_pred_svm=svm_classifier.predict(x_test)

In [35]:
print('Accuracy is : '), accuracy_score(y_test,y_pred_svm)*100

Accuracy is : 


(None, 99.0)