In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
companies = pd.read_csv("1000_Companies.csv")

In [3]:
companies.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
x=companies.drop(columns=['Profit']).values
y=companies['Profit'].values

In [5]:
print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 ...
 [100275.47 241926.31 227142.82 'California']
 [128456.23 321652.14 281692.32 'California']
 [161181.72 270939.86 295442.17 'New York']]


In [6]:
print(y)

[192261.83    191792.06    191050.39    182901.99    166187.94
 156991.12    156122.51    155752.6     152211.77    149759.96
 146121.95    144259.4     141585.52    134307.35    132602.65
 129917.04    126992.93    125370.37    124266.9     122776.86
 118474.03    111313.02    110352.25    108733.99    108552.04
 107404.34    105733.54    105008.31    103282.38    101004.64
  99937.59     97483.56     97427.84     96778.92     96712.8
  96479.51     90708.19     89949.14     81229.06     81005.76
  78239.91     77798.83     71498.49     69758.98     65200.33
  64926.08     49490.75     42559.73     35673.41     14681.4
 123485.2464   82155.48418 125867.0108  104976.1696   89803.10053
  75297.23305 114284.5283  171985.0761   72337.96774 169566.5772
 158670.9451  114522.8756   85842.60573 101106.2297   59328.81874
 157142.6178   68669.64059 177717.3712   94409.4396  183945.1553
  82484.38635 144515.3371  105333.2634  122331.0988  168459.4156
  60947.70089 162733.9549  181574.4968   7357

#Data Preprocessing

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [8]:
labelencoder=LabelEncoder()

In [9]:
x[:, 3]=labelencoder.fit_transform(x[:, 3])# which column is categorical 

In [10]:
onehot_encoder = OneHotEncoder(categories='auto',sparse=False)
x[:, 3]= onehot_encoder.fit_transform(x[:, 3])

C:\Users\irumj\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [11]:
print(x)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


Splitting Data

In [13]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
regressor=LinearRegression()

In [18]:
regressor.fit(x_train,y_train)

LinearRegression()

In [20]:
y_pred=regressor.predict(x_test)

In [21]:
print(y_pred)

[121197.62455694 119338.5234664  119826.05029282 118723.9477665
 115674.65074559 117477.17055888 118576.18008231 120494.50492056
 117647.11793069 111428.1812526  116326.12629002 118757.67857551
 120238.31795133 113647.87269831 119756.73886715 114767.17816744
 118935.45680527 119756.73886715 118738.40440398 117647.11793069
 118187.94944314 120796.78676234 118723.9477665  119099.81602938
 119568.8483419  119967.11713179 120029.07485492 127008.80424384
 118846.75016459 119756.73886715 118484.13734174 119837.45988189
 117111.67049852 118522.32594379 120225.78308385 119175.54826156
 117647.11793069 118723.9477665  118723.9477665  119413.76241752
 117920.13000974 119756.73886715 119911.03103817 116618.17941391
 118921.32803125 130980.91816936 118679.15796127 121191.38353153
 118716.16418572 118998.60329119 118723.9477665  118723.9477665
 120200.42707729 119165.23979379 179180.34966418 116626.10179977
 118778.61498326 117647.11793069 118070.22792564 117787.86633979
 118877.71908528 110878.536